name: movie_list
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  cloud_firestore: ^4.11.0
  firebase_core: ^2.19.0
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0

flutter:

  uses-material-design: true
