// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ5-fYK8U0RqMuwp10y-siaI3ob2-4-B8',
    appId: '1:99846774696:web:a7768c6f197650c3dd879d',
    messagingSenderId: '99846774696',
    projectId: 'searchmovie-5881b',
    authDomain: 'searchmovie-5881b.firebaseapp.com',
    storageBucket: 'searchmovie-5881b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVkk5DCt_qEXp5QldZ9gVt2V0pphx8U-s',
    appId: '1:99846774696:android:cf48651927d97591dd879d',
    messagingSenderId: '99846774696',
    projectId: 'searchmovie-5881b',
    storageBucket: 'searchmovie-5881b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAajc4hSXUEdmbWmpjJMqXnQFzbi_rGUlU',
    appId: '1:99846774696:ios:875a6ccbda754085dd879d',
    messagingSenderId: '99846774696',
    projectId: 'searchmovie-5881b',
    storageBucket: 'searchmovie-5881b.appspot.com',
    iosBundleId: 'com.example.movieList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAajc4hSXUEdmbWmpjJMqXnQFzbi_rGUlU',
    appId: '1:99846774696:ios:2d0e0ea5a5e6f715dd879d',
    messagingSenderId: '99846774696',
    projectId: 'searchmovie-5881b',
    storageBucket: 'searchmovie-5881b.appspot.com',
    iosBundleId: 'com.example.movieList.RunnerTests',
  );
}
